language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra
    - addon
    - sys-img-armeabi-v7a-android-18

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo no | android create avd --force --name test --target android-18 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - jdk_switcher use openjdk7
  - jdk_switcher use oraclejdk8
  - ./gradlew assemble test -PdisablePreDex
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck  -PdisablePreDex

after_success:
  - ./gradlew jacocoTestReport coveralls
