language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - jdk_switcher use openjdk7
  - jdk_switcher use oraclejdk8
  - ./gradlew assemble test

after_success:
  - ./gradlew jacocoTestReport coveralls
